NUM_SIMULATIONS = 50
EPSILON = 0.3
EPSILON_DECAY = 0.5
CONSTANT = 0.5

BOARD_SIZE = 4

RELEASE = False

def enable_release():
    global RELEASE
    RELEASE = True

REGULARIZER = 0.00001
LEARNING_RATE = 0.01
INPUT_DIM = (BOARD_SIZE, BOARD_SIZE, 3)
OUTPUT_DIM = BOARD_SIZE ** 2
MOMENTUM = 0.8

HIDDEN = [{'filters': 128, 'kernel_size': (3, 3)} for _ in range(20)]

TRAIN_ITERS = 5
RANDOM_SAMPLES = 1000 # :O
EPOCHS = 15
VERBOSE = 2
VALIDATION_SPLIT = 0.2
BATCH_SIZE = 256